simplemooc/accounts/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_view

from . import views

urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path('signup/', views.register, name='signup'),
    path('edit/', views.edit, name='edit'),
    path('edit/password/', views.edit_password, name='edit_password'),
    path('reset-password/', views.password_reset, name='password_reset'),
    path('confirm-password/<key>/', views.password_reset_confirm, name='password_reset_confirm'),
    path('signin/', auth_view.LoginView.as_view(template_name='accounts/signin.html'), name='signin'),
    path('logout/', auth_view.LogoutView.as_view(next_page='core:home'), name='logout'),
]

simplemooc/core/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
]

simplemooc/forum/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('tag/<tag>/', views.index, name='index_tagged'),
    path('replies/<pk>/correct/', views.reply_correct, name='reply_correct'),
    path('respostas/<pk>/incorrect/', views.reply_incorrect, name='reply_incorrect'),
    path('<slug:slug>/', views.thread, name='thread'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from simplemooc.core import urls
from simplemooc.courses import urls as courses_urls
from simplemooc.accounts import urls as accounts_urls
from simplemooc.forum import urls as forums_urls

admin.autodiscover()

urlpatterns = [
    path('', include((urls, 'core'), namespace='core')),
    path('courses/', include((courses_urls, 'courses'), namespace='courses')),
    path('account/', include((accounts_urls, 'account'), namespace='account')),
    path('forum/', include((forums_urls, 'forum'), namespace='forum')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

simplemooc/core/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
  return render(request, 'home.html', {'usuario': 'user@name.co'})

def contact(request):
  return render(request, 'contact.html')

simplemooc/core/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Simple MOOC - Uma simples plataforma de ensino a distância" />
    <title>Simple MOOC</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
</head>
<body>
<div class="header">
    <div class="home-menu pure-menu pure-menu-open pure-menu-horizontal pure-menu-fixed">
        <a class="pure-menu-heading" href="{% url 'core:home' %}">SIMPLE MOOC</a>
        <ul>
            <li class="pure-menu-selected"><a href="{% url 'core:home' %}">Home</a></li>
            <li><a href="{% url 'courses:index' %}">Courses</a></li>
            <li><a href="{% url 'core:contact' %}">Contact</a></li>
            <li><a href="{% url 'forum:index' %}">Forum</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'account:dashboard' %}">Dashboard</a></li>
            <li><a href="{% url 'account:logout' %}">Sign out</a></li>
            {% else %}
            <li><a href="{% url 'account:signin' %}">Sign in</a></li>
            {% endif %}
        </ul>
    </div>
</div>
<div class="content">
    {% if messages %}
    <div class="pure-g-r content-ribbon">
        <aside class="pure-u-1">
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
        </aside>
    </div>
    {% endif %}
    {% block content %}{% endblock %}
    <div class="footer">
        Simple MOOC - Simple Massive Open On-line Course
    </div>
</div>
<script src="http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
{% block scripts %}{% endblock %}
</body>
</html>

simplemooc/core/templates/contact.html
{% extends 'base.html' %}
{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h1>Contact Us</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto alias ducimus, maxime, obcaecati officiis tempore consequuntur culpa adipisci rerum accusantium, totam beatae aperiam consectetur sit:</p>
        <h4>Links</h4>
        <ul>
            <li>E-mail: <a href="mailto:contact@simplemooc.org">contact@simplemooc.org</a></li>
            <li>Twitter: <a href="https://twitter.com/simplemooc">@simplemooc</a></li>
        </ul>
    </div>
</div>
  {% endblock %}

simplemooc/core/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="splash">
  <div class="pure-g-r">
    <div class="pure-u-1">
      <div class="l-box splash-text">
        <h1 class="splash-head">
          Simple Massive Open On-line Course
        </h1>
        <h2 class="splash-subhead">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. 
          Perferendis vero velit assumenda soluta modi aut?.
        </h2>
        <p>
          <a href="#" class="pure-button primary-button">Learn more</a>
        </p>
      </div>
    </div>
  </div>
</div>
<div class="content">
  <div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
      <div class="l-box">
        <h4 class="content-subhead">Virtual online classes with videos and quizzes</h4>
        <h3>Publish classes</h3>
        <p>
          Simple MOOC have a easy and pratical environment 
          for you, the professor, to make you classes available. 
        </p>
      </div>
    </div>
    <div class="pure-u-1-3">
      <div class="l-box">
        <img
          src="http://placehold.it/400x250"
          alt="Vídeo aulas e materiais digitais."
        />
      </div>
    </div>
  </div>
  <div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
      <div class="l-box">
        <img src="http://placehold.it/400x250" alt="FAQ" />
      </div>
    </div>
    <div class="pure-u-2-3">
      <div class="l-box">
        <h4 class="content-subhead">Keep in touch</h4>
        <h3>Iteract with students</h3>
        <p>
          At Simple MOOC you have your own forum-like board,
          to keep in touch with your students and for them to iteract with each other
        </p>
      </div>
    </div>
  </div>
  <div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
      <div class="l-box">
        <h4 class="content-subhead">Quizzes</h4>
        <h3>Create quizzes to evalute your students</h3>
        <p>
          Evaluate your students creating quizzes.
          Follow up their grades, and manage their progress
        </p>
      </div>
    </div>
    <div class="pure-u-1-3">
      <div class="l-box">
        <img src="http://placehold.it/400x250" alt="Quizzes" />
      </div>
    </div>
  </div>
  <div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
      <div class="l-box">
        <img src="http://placehold.it/400x250" alt="Messages" />
      </div>
    </div>
    <div class="pure-u-2-3">
      <div class="l-box">
        <h4 class="content-subhead">Messages</h4>
        <h3>Broadcast messages for your students</h3>
        <p>
          Send out warning, message and more in the most easy way possible.
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}