simplemooc/accounts/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_view

from . import views

urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path('signup/', views.register, name='signup'),
    path('edit/', views.edit, name='edit'),
    path('edit/password/', views.edit_password, name='edit_password'),
    path('reset-password/', views.password_reset, name='password_reset'),
    path('confirm-password/<key>/', views.password_reset_confirm, name='password_reset_confirm'),
    path('signin/', auth_view.LoginView.as_view(template_name='accounts/signin.html'), name='signin'),
    path('logout/', auth_view.LogoutView.as_view(next_page='core:home'), name='logout'),
]

simplemooc/courses/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.courses, name='index'),
    path('<slug:slug>', views.detail, name='detail'),
    path('<slug:slug>/enroll/', views.enrollment, name='enrollment'),
    path('<slug:slug>/enroll/cancel', views.undo_enrollment, name='undo_enrollment'),
    path('<slug:slug>/announcements/', views.announcements, name='announcements'),
    path('<slug:slug>/announcements/<pk>/', views.show_announcement, name='show_announcement'),
    path('<slug:slug>/lessons/', views.lessons, name='lessons'),
    path('<slug:slug>/lesson/<pk>/', views.lesson, name='lesson'),
    path('<slug:slug>/materials/<pk>/', views.material, name='material'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from simplemooc.core import urls
from simplemooc.courses import urls as courses_urls
from simplemooc.accounts import urls as accounts_urls
from simplemooc.forum import urls as forums_urls

admin.autodiscover()

urlpatterns = [
    path('', include((urls, 'core'), namespace='core')),
    path('courses/', include((courses_urls, 'courses'), namespace='courses')),
    path('account/', include((accounts_urls, 'account'), namespace='account')),
    path('forum/', include((forums_urls, 'forum'), namespace='forum')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

simplemooc/accounts/models.py
import re

from django.db import models
from django.core import validators
from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin,
    UserManager)
from django.conf import settings


class User(AbstractBaseUser, PermissionsMixin):
  username = models.CharField(
    'User Name', max_length=30, unique=True, 
    validators=[validators.RegexValidator(re.compile(r'^[\w.@+-]+$'),
      'User name can only have letters, numbers or '
      'the following: @/./+/-/_', 'invalid')]
  )
  email = models.EmailField('E-mail', unique=True)
  name = models.CharField('Name', max_length=100, blank=True)
  is_active = models.BooleanField('Active?', blank=True, default=True)
  is_staff = models.BooleanField('Staff?', blank=True, default=False)
  date_joined = models.DateTimeField('Join date', auto_now_add=True)

  objects = UserManager()

  USERNAME_FIELD = 'username'
  REQUIRED_FIELDS = ['email']

  def __str__(self):
      return self.name or self.username

  def get_short_name(self):
      return self.username

  def get_full_name(self):
      return str(self)

  class Meta:
      verbose_name = 'User'
      verbose_name_plural = 'Users'

class PasswordReset(models.Model):
  user = models.ForeignKey(settings.AUTH_USER_MODEL,
    on_delete=models.DO_NOTHING,
    verbose_name='User',
    related_name='resets'
  )
  key = models.CharField('Key', max_length=100, unique=True)
  created_at = models.DateTimeField('Created at', auto_now_add=True)
  confirmed = models.BooleanField('Confirmed?', default=False, blank=True)

  def __str__(self):
      return '{0} at {1}'.format(self.user, self.created_at)

  class Meta:
      verbose_name = 'New Password'
      verbose_name_plural = 'New Passwords'
      ordering = ['-created_at']

simplemooc/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from simplemooc.core.mail import send_mail_template
from simplemooc.core.utils import generate_hash_key

from .models import PasswordReset

User = get_user_model()

class PasswordResetForm(forms.Form):
  email = forms.EmailField(label='E-mail')

  def clean_email(self):
    email = self.cleaned_data['email']
    if User.objects.filter(email=email).exists():
        return email
    raise forms.ValidationError(
        'No User found for given e-mail'
    )

  def save(self):
    user = User.objects.get(email=self.cleaned_data['email'])
    key = generate_hash_key(user.username)
    reset = PasswordReset(key=key, user=user)
    reset.save()
    template_name = 'accounts/password_reset_mail.html'
    subject = 'Simple MOOC - New Password'
    context = {
        'reset': reset,
    }
    send_mail_template(subject, template_name, context, [user.email])

class RegisterForm(forms.ModelForm):
  password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
  password2 = forms.CharField(
    label='Password confirmtion', widget=forms.PasswordInput
  )

  def clean_password2(self):
    password1 = self.cleaned_data.get("password1")
    password2 = self.cleaned_data.get("password2")
    if password1 and password2 and password1 != password2:
        raise forms.ValidationError('Password don`t match')
    return password2

  def save(self, commit=True):
    user = super(RegisterForm, self).save(commit=False)
    user.set_password(self.cleaned_data['password1'])
    if commit:
        user.save()
    return user

  class Meta:
    model = User
    fields = ['username', 'email']


class EditAccountForm(forms.ModelForm):
  class Meta:
    model = User
    fields = ['username', 'email', 'name']

simplemooc/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import (UserCreationForm, PasswordChangeForm,
    SetPasswordForm)
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.conf import settings

from simplemooc.core.utils import generate_hash_key

from .forms import RegisterForm, EditAccountForm, PasswordResetForm
from .models import PasswordReset

User = get_user_model()

@login_required
def dashboard(request):
  template_name = 'accounts/dashboard.html'
  return render(request, template_name)

def register(request):
  template_name = 'accounts/register.html'
  if request.method == 'POST':
    form = RegisterForm(request.POST)
    if form.is_valid():
      user = form.save()
      user = authenticate(
          username=user.username, password=form.cleaned_data['password1']
      )
      login(request, user)
      return redirect('core:home')
  else:
      form = RegisterForm()
  context = {
      'form': form
  }
  return render(request, template_name, context)

def password_reset(request):
  template_name = 'accounts/password_reset.html'
  context = {}
  form = PasswordResetForm(request.POST or None)
  if form.is_valid():
    form.save()
    context['success'] = True
  context['form'] = form
  return render(request, template_name, context)

def password_reset_confirm(request, key):
  template_name = 'accounts/password_reset_confirm.html'
  context = {}
  reset = get_object_or_404(PasswordReset, key=key)
  form = SetPasswordForm(user=reset.user, data=request.POST or None)
  if form.is_valid():
      form.save()
      context['success'] = True
  context['form'] = form
  return render(request, template_name, context)



@login_required
def edit(request):
  template_name = 'accounts/edit.html'
  context = {}
  if request.method == 'POST':
      form = EditAccountForm(request.POST, instance=request.user)
      if form.is_valid():
          form.save()
          form = EditAccountForm(instance=request.user)
          context['success'] = True
  else:
      form = EditAccountForm(instance=request.user)
  context['form'] = form
  return render(request, template_name, context)

@login_required
def edit_password(request):
  template_name = 'accounts/edit_password.html'
  context = {}
  if request.method == 'POST':
      form = PasswordChangeForm(data=request.POST, user=request.user)
      if form.is_valid():
          form.save()
          context['success'] = True
  else:
      form = PasswordChangeForm(user=request.user)
  context['form'] = form
  return render(request, template_name, context)

simplemooc/accounts/templates/accounts/dashboard.html
{% extends "base.html" %}

{% load courses_tags %}

{% block content %}
{% load_my_courses user as enrollments %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb">
            {% block breadcrumb %}
            <li><a href="{% url 'account:dashboard' %}">My Dashboard</a></li>
            {% endblock %}
        </ul>
    </div>
    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open">
            <ul>
                <li class="pure-menu-heading">
                    Bem-vindo, {{ user }}
                </li>
                {% block menu_options %}
                <li class="pure-menu-heading">Cursos</li>
                {% for enrollment in enrollments %}
                <li>
                    <a href="{% url 'courses:announcements' enrollment.course.slug %}">
                    <i class="fa fa-book"></i>
                    {{ enrollment.course }}
                    </a>
                </li>
                {% empty %}
                <li>Nenhum curso encontrado</li>
                {% endfor %}
                <li class="pure-menu-heading">Account</li>
                <li>
                    <a href="{% url 'account:edit' %}">
                    <i class="fa fa-cog"></i>
                    Edit
                    </a>
                </li>
                <li>
                    <a href="{% url 'account:edit_password' %}">
                    <i class="fa fa-lock"></i>
                    Change Password
                    </a>
                </li>
                {% endblock %}
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            {% block dashboard_content %}
            <h2>My Enrollments</h2>
            {% for enrollment in enrollments %}
            <div class="well">
                <h3>{{ enrollment.course }}
                ({{ enrollment.course.start_date|date:'d/m/Y'|default:'Sem data' }})
                </h3>
                {{ enrollment.course.description|linebreaks }}
                <div class="pure-controls">
                    <a href="{% url 'courses:announcements' enrollment.course.slug %}" class="pure-button pure-button-primary">Access</a>
                    <a href="{% url 'courses:undo_enrollment' enrollment.course.slug %}" class="pure-button button-error">Cancel</a>
                </div>
            </div>
            {% empty %}
            <aside class="pure-u-1">
                <p>No enrollments yet</p>
            </aside>
            {% endfor %}

            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/edit.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'account:edit' %}">Edit</a></li>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    {% if success %}
    <p>You account has been updated.</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Save changes</button>
        </div>
    </fieldset>
</form>
{% endblock %}

simplemooc/accounts/templates/accounts/edit_password.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'account:edit_password' %}">Change Password</a></li>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    {% if success %}
    <p>Sucess ! You changed your password.</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Change password</button>
        </div>
    </fieldset>
</form>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        {% if success %}
        <p>An e-mail was sent to you with more details on how to create a new password</p>
        {% else %}
        <h2>E-mail</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Send E-mail</button>
                </div>
            </fieldset>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        {% if success %}
        <p>Sucess ! Your password was changed</p>
        {% else %}
        <h2>New password</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Reset</button>
                </div>
            </fieldset>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset_mail.html
<p>To create a new password, follow the link: 
  <a href="http://127.0.0.1:8000{% url 'account:password_reset_confirm' reset.key %}" title="Link for new Password creator">Create new Password</a>
</p>

simplemooc/accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Your information</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Register</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/signin.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Inform your credentials</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Sign in</button>
                </div>
            </fieldset>
            <p>
                New around here? <a href="{% url 'account:signup' %}" title="">Register now</a> <br />
                Forgot password? <a href="" title="">New password</a> <br />
            </p>
        </form>
    </div>
</div>
{% endblock %}